### ISSUE TITLE
AttributeError: class DWServer has no attribute 'mcErr'

### ISSUE THREAD

**Issue by linuxha** [n6il/pyDriveWire#1]
Recieved this when I did an LLIST on my MC-10 (MCX BASIC)

Traceback (most recent call last):
  File "./pyDriveWire.py", line 104, in <module>
    dws.main()
  File "/home/njc/dev/git/pyDriveWire/dwserver.py", line 907, in main
    f(self,cmd)
  File "/home/njc/dev/git/pyDriveWire/dwserver.py", line 853, in doEmCeeCmd
    f(self, mccmd)
  File "/home/njc/dev/git/pyDriveWire/dwserver.py", line 852, in <lambda>
    f= lambda s,x: DWServer.mcErr(s,x)
AttributeError: class DWServer has no attribute 'mcErr'

I think you might need to change mcErr to cmdErr
dwserver.py line 852 mcErr change to  cmdErr

**Comment by n6il** [comment]
I will take a look, thanks for the report.

**Comment by n6il** [comment]
The "Virtual Printer" feature described in the _Emcee File Server For use with the TRS-80 MC-10 and MCX Basic_ manual, but there is no mention of it in the _MCX BASIC SERIAL PORT FILE PROTOCOL_ manual.  I will have to reverse engineer it to figure out what it's actually doing.

**Comment by linuxha** [comment]
I can help, what do you recommend to add to the code to help?

**Comment by linuxha** [comment]
I was taking a peak (turned on debug) and I see:

serread: len=1 len: 1
0000: |21                               | |!                |
serread: len=1 len: 1
0000: |50                               | |P                |
serread: len=1 len: 1
0000: |30                               | |0                |

serread: len=1 len: 1
0000: |21                               | |!                |
serread: len=1 len: 1
0000: |50                               | |P                |
serread: len=1 len: 1
0000: |20                               | |.                |

serread: len=1 len: 1
0000: |21                               | |!                |
serread: len=1 len: 1
0000: |50                               | |P                |
serread: len=1 len: 1
0000: |52                               | |R                |

serread: len=1 len: 1
0000: |21                               | |!                |
serread: len=1 len: 1
0000: |50                               | |P                |
serread: len=1 len: 1
0000: |45                               | |E                |

serread: len=1 len: 1
0000: |21                               | |!                |
serread: len=1 len: 1
0000: |50                               | |P                |
serread: len=1 len: 1
0000: |4d                               | |M                |

serread: len=1 len: 1
0000: |21                               | |!                |
serread: len=1 len: 1
0000: |50                               | |P                |
serread: len=1 len: 1
0000: |0d                               | |.                |

Whis is the first lien of the BASIC program:
[0 REM\r] (where \r is a Carriage Return or hex 0x0D)
But sent as"
[!P0!P !PR!PE!PM!P\r]
So it seems each character is send as "!" "P" character
Hope that helps a bit

**Comment by n6il** [comment]
Fixed in pyDriveWire v0.5 release
