### ISSUE TITLE
Default file extension in Emcee server?

### ISSUE THREAD

**Issue by BlairLeduc** [n6il/pyDriveWire#4]
In the "official" Emcee server on macOS, you can type load"file" on the MC-10 and the server will add the .c10 extension for you.  Could we have that for pyDriveWire as well?

**Comment by n6il** [comment]
Both .C10, .CAS are supported.

https://github.com/n6il/pyDriveWire/blob/master/docs/The%20pyDriveWire%20Manual.md#ch9
